[package]
name = "hubcaps"
version = "0.3.16"
authors = ["softprops <d.tangren@gmail.com>"]
description = "Rust interface for Github"
documentation = "https://softprops.github.io/hubcaps"
homepage = "https://github.com/softprops/hubcaps"
repository = "https://github.com/softprops/hubcaps"
keywords = ["hyper", "github"]
license = "MIT"
categories = ["api-bindings", "web-programming::http-client"]
readme = "README.md"

[badges]
travis-ci = { repository = "softprops/hubcaps" }

[dev-dependencies]
env_logger = "0.3"
hyper-native-tls = "0.2"

[dependencies]
log = "0.3"
hyper = "0.10"
url = "1.2"
serde = "1"
serde_derive = "1"
serde_json = "1"
error-chain = "0.10"
frank_jwt = "3.0.2"
